### ISSUE TITLE
missing test case for high cards

### ISSUE THREAD

**Issue by mebusw** [terryyin/CodingExercises#1]
```
what if below hands?

HighCard = PokerHand("2H 4H 5H 7H 9D")
BiggerHighCard = PokerHand("2H 3H 7H 8H 9D")
```

**Comment by terryyin** [comment]
I don't think it's a missing case:-) Try deleting any line of my code and run the test again. See if you can fail my tests...

But I do agree your HighCard example is better, I took the suggest:-)

Thanks.

Your HighCard example is better, but the solution doesn't change

**Comment by mebusw** [comment]
what about this case:
此牌由五张顺序扑克牌组成，如果不止一人有此牌组，则五张牌中点数最大的赢得此局，10-J-Q-K-A为最大的顺子，A-2-3-4-5为最小的顺子。
http://zh.wikipedia.org/wiki/%E5%BE%B7%E5%B7%9E%E6%92%B2%E5%85%8B

**Comment by terryyin** [comment]
oh, ok... That's interesting.

**Comment by terryyin** [comment]
OK, updated.
